---
- name: Ping
  hosts: win_victor.finance.lab

  tasks:
    - name: ping win_victor
      win_ping:
      register: ping_results
    
    - name: report results ping
      debug:
        var: ping_results
